# Site settings
title: Saurabh Londhe|Blog
description: Saurabh Londhe is an Computer Engineer. Love to work in Python and DevOps. Aware of Cloud and Container Technologies like AWS, Docker, Azure, Aneka, etc
keywords: Blogs,Saurabh Londhe,Open Source,Web,Git
author: Saurabh Londhe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
paginate: 6
paginate_path: /page:num/
plugins:
  - jemoji